export const COLORS = {
  primaryBackgroundColor: '#212328',
  secondaryBackgroundColor: '#2F323A',
  textPrimaryColor: 'white',
  textSecondaryColor: '#BECAE8',
  buttonPrimaryColor: '#FED32B',
  buttonPrimaryPressedColor: '#927907',
  buttonSecondaryColor: '#BECAE8',
  buttonSecondaryPressedColor: '#99A7C4',
  buttonPrimaryTextColor: '#212328',
  arrowButtonColor: '#2B3138',
  arrowButtonPressedColor: '#525354',
  arrowColor: '#FED32B',
  arrowColorInactive: '#74767E',
  inputBorderColor: '#74767E',
  inputBackgroundColor: '#2F323A',
  shadowColor: 'black',
  errorColor: '#FF6B6B',
};
