export const COLORS = {
  primaryBackgroundColor: '#212328',
  secondaryBackgroundColor: '#4D525E',
  textPrimaryColor: 'white',
  textSecondaryColor: '#BECAE8',
  buttonPrimaryColor: '#FED32B',
  buttonPrimaryPressedColor: '#E6C21B',
  buttonSecondaryColor: '#BECAE8',
  buttonSecondaryPressedColor: '#99A7C4',
  buttonPrimaryTextColor: '#212328',
  arrowButtonColor: '#2B3138',
  arrowButtonPressedColor: '#525354',
  arrowColor: '#FED32B',
  arrowColorInactive: '#74767E',
  inputBorderColor: 'white',
  shadowColor: 'black',
};
