name: Deployment
on:
  push:
    branches: [main]
    paths-ignore:
      - 'apps/mobile/**'
      - 'pnpm-lock.yaml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'apps/mobile/**'
      - 'pnpm-lock.yaml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
