name: Test and deploy 🚀
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installs pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.x.x

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Type checking
        run: pnpm tsc

      - name: Lint code
        run: pnpm lint

      - name: Deploy to production
        run: |
          npx vercel link --yes --token=${{ secrets.VERCEL_TOKEN }} --project killer-front
          npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
