name: Deploying web app

on:
  push:
    paths:
      - 'apps/web/**'
    branches: [main]

jobs:
  web:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build packages
        run: npm build

      - name: Type checking
        run: npm tsc --filter=./apps/web

      - name: Lint code
        run: npm lint

      - name: Deploy to production
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
