name: Deploying web app

on:
  push:
    paths:
      - 'web/**'
    branches: [main]

jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Copy Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build packages
        run: npm run build

      - name: Type checking
        run: npm run typecheck

      - name: Lint code
        run: npm run lint

      - name: Deploy to production
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
